Repository ron010-1/criancaFeliz-pw1, pull requests merged in 2025-08, with the labels that each got.

#2 feat: adicionando pacotes e funcao de login e verifytoken jwt
  index.js
  package-lock.json
  package.json
  src/@types/express.d.ts
  src/config/createDefaultAdmin.ts
  src/config/envConfig.ts
  src/controller/assisenteSocial.controller.ts
  src/controller/beneficiario.controller.ts
  src/controller/login.controller.ts
  src/middlewares/verifyJwt.middleware.ts
  src/models/Admin.model.ts
  src/models/AssistenteSocial.model.ts
  src/routes/assistenteSocial.route.ts
  src/routes/beneficiario.route.ts
  src/routes/login.route.ts
  src/server.ts
  src/service/admin.service.ts
  src/service/assistenteSocial.service.ts
  src/service/beneficiario.service.ts
  src/utils/hashPassword.ts
  src/utils/validatePassword.ts
Labels: enhancement, good first issue, wontfix

#3 Feat/visita
  src/controller/assisenteSocial.controller.ts
  src/controller/visita.controller.ts
  src/middlewares/verifyJwt.middleware.ts
  src/models/AssistenteSocial.model.ts
  src/models/Beneficiario.model.ts
  src/models/Visita.model.ts
  src/routes/assistenteSocial.route.ts
  src/routes/beneficiario.route.ts
  src/routes/visita.route.ts
  src/server.ts
  src/service/assistenteSocial.service.ts
  src/service/visita.service.ts
Labels: good first issue

#5 fix: resolvendo erro de verifytoken em visitas
  src/routes/visita.route.ts
Labels: enhancement, good first issue

#6 eu fiz o crud de visita
  src/controller/visita.controller.ts
  src/models/Imagem.model.ts
  src/service/visita.service.ts
Labels: enhancement, good first issue
